Repository arlonproj/arlon, pull requests merged in 2022-11, with the labels that each got.

#289 Fix makefile for v0.3 to add target pkgtest used by goreleaser
  Makefile
Labels: bug, size:xs, sprint8

#292 Update v0.9 to use the latest patch v2.4.16 for ArgoCD lib v2.4
  go.mod
  go.sum
Labels: size:xs, sprint8

#239 Fix #238: Set RootFS ReadOnly False
  deploy/manifests/deploy.yaml
Labels: bug, sprint8

#288 Minor fixes in arlon setup script
  setup_arlon.sh
Labels: bug

#294 [Backport to v0.9] Fix #238: Set RootFS ReadOnly False (#239)
  deploy/manifests/deploy.yaml
Labels: bug, size:xs, sprint8

#324 Change Arlon logo bg color to white , for better visibility with light as well as dark theme
  docs/images/logo_arlon.svg
Labels: bug, size:xs, UX, sprint10

#331 Backport to v0.3 : Fix #238: Set RootFS ReadOnly False (#239)
  deploy/manifests/deploy.yaml
Labels: bug, in_code_review, sprint10

#332 For release v0.3.8 : Bump ArgoCD lib to v2.2.16, k8s libs to v0.22.16 and bump Arlon version to 0.3.8
  docs/requirements.txt
  go.mod
  go.sum
  version
Labels: dependencies, size:xs, sprint10

#333 Use another GitHub token from GoReleaser action
  .github/workflows/goreleaser.yaml
Labels: bug, sprint10, sprint11

#315 Documentation changes in installation and tutorial
  README.md
  docs/README.md
  docs/architecture.md
  docs/baseclusters.md
  docs/concepts.md
  docs/contributing.md
  docs/design.md
  docs/dev_setup.md
  docs/docs_help.md
  docs/e2e_testing.md
  docs/gen2_Tutorial.md
  docs/installation.md
  docs/tutorial.md
  mkdocs.yml
Labels: documentation, sprint9

#327 Update CI to enable code coverage reporting
  .github/workflows/ci.yml
  codecov.yml
  pkg/basecluster/data.go
Labels: enhancement
