Repository arlonproj/arlon, pull requests merged in 2022-08, with the labels that each got.

#128 Chore: Update Dockerfile to use the latest golang 1.17 patch
  Dockerfile
Labels: sprint1, size:xs

#129 Chore: Arlon v0.3 : Update Dockerfile to use the latest golang 1.17 p…
  Dockerfile
Labels: enhancement, good first issue, dependencies

#126 Create dependabot.yml GH action to enable updates with DependaBot
  .github/dependabot.yml
Labels: enhancement, dependencies, size:S, sprint1

#127 Chore: Update Trivy scanner
  .github/workflows/trivy.yml
Labels: enhancement, good first issue, dependencies, size:xs

#141 Port changes from v0.3 into main
  .gitignore
  Makefile
  cmd/clusterspec/create.go
  controllers/callhomeconfig_controller.go
  controllers/clusterregistration_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  pkg/clusterspec/create.go
  pkg/clusterspec/utils.go
  version
Labels: enhancement, sprint1, size:xs

#139 v0.3 : Fix installation of CRDs in README.md
  README.md
Labels: bug, documentation

#142 port to main: Fix installation of CRDs in README
  README.md
Labels: documentation, size:xs

#175 Commands to build Arlon CLI locally and cross-compile for other CPU, OSes
  Makefile
Labels: enhancement, size:xs

#177 Deploy the latest of v0.3 (v0.3.5) not v0.3.0 image of Arlon
  deploy/manifests/deploy.yaml
Labels: bug

#174 Add goreleaser github action
  .github/workflows/goreleaser.yaml
  .goreleaser.yaml
  Makefile
Labels: enhancement

#180 Release automation for v0.3x tags
  .github/workflows/goreleaser.yaml
  .goreleaser.yaml
Labels: enhancement

#165 Add support for k8s 1.23 and ArgoCD 2.4 client libraries in Arlon
  Dockerfile
  Makefile
  api/v1/groupversion_info.go
  config/crd/bases/core.arlon.io_callhomeconfigs.yaml
  config/crd/bases/core.arlon.io_clusterregistrations.yaml
  config/crd/bases/core.arlon.io_profiles.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  pkg/basecluster/prepare_test.go
  pkg/basecluster/preparegit_test.go
  pkg/basecluster/validate_test.go
  pkg/cluster/cluster_app.go
  pkg/cluster/create.go
  pkg/cluster/delete.go
  pkg/cluster/external.go
  pkg/cluster/list.go
  pkg/cluster/profile_app.go
Labels: enhancement, dependencies

#184 Update requirements.txt for mkdocs (ReadTheDocs, GitHub pages)
  docs/requirements.txt
Labels: bug

#185 Update main README.md
  README.md
Labels: documentation

#188 Update deploy.yaml
  deploy/manifests/deploy.yaml
Labels: bug

#187 Update Makefile to fix warnings
  Makefile
Labels: bug

#186 Update ci.yml to use go v1.19 and listed improvements
  .github/workflows/ci.yml
Labels: enhancement
