Repository arlonproj/arlon, pull requests merged in 2022-12, with the labels that each got.

#340 Fix Gen2 tutorial
  docs/gen2_Tutorial.md
  pkg/cluster/ngupdate.go
Labels: size:xs, UX, in_code_review, sprint12

#341 Backport static profile validation in ngupdate, doc fix for ngupdate
  .gitignore
  README.md
  deploy/manifests/deploy.yaml
  docs/baseclusters.md
  pkg/cluster/ngupdate.go
  version
Labels: in_code_review

#342 fix goreleaser for v0.9
  .github/workflows/goreleaser.yaml
Labels: in_code_review

#338 Update init.go - Bump defaultK8sVersion from 1.23.11 to 1.23.14
  cmd/initialize/init.go
Labels: size:xs, sprint11

#336 Update GitHub Actions for higher rate limit in setup-go action
  .github/workflows/ci.yml
  .github/workflows/e2e.yaml
  .github/workflows/goreleaser.yaml
Labels: size:xs, in_code_review, sprint12, sprint11

#347 Arlon readme edits
  README.md
Labels: documentation, size:xs, in_code_review, sprint12

#366 Updates to arlon docs
  docs/README.md
  docs/images/favicon-16x16.png
  docs/images/favicon-32x32.png
  docs/images/logo_arlon-stroke.svg
  docs/images/pictogram_arlon-stroke.svg
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: documentation, size:xs

#369 Versioning of docs
  docs/requirements.txt
  mkdocs.yml
  overrides/main.html
Labels: documentation, sprint13

#354 Cluster Autoscaler(CAS) fix for Gen1, add CAS support for gen2 clusters
  .github/workflows/ci.yml
  .gitignore
  Makefile
  cmd/basecluster/prepare.go
  cmd/basecluster/preparegit.go
  cmd/cluster/create.go
  cmd/cluster/deploy.go
  controllers/callhomeconfig_controller.go
  pkg/basecluster/prepare.go
  pkg/basecluster/prepare_test.go
  pkg/basecluster/preparegit_test.go
  pkg/cluster/create.go
  pkg/cluster/manifests/charts/capi-aws-eks/templates/cluster.yaml
  pkg/cluster/manifests/charts/capi-cluster-autoscaler/templates/callhomeconfig.yaml
  pkg/cluster/manifests/charts/capi-cluster-autoscaler/templates/rbac.yaml
  pkg/cluster/manifests/values.yaml
  pkg/cluster/root_app.go
  pkg/cluster/update.go
Labels: bug, enhancement, in_code_review, sprint12, sprint13

#367 Separate documentation for v0.9
  README.md
  docs/README.md
  docs/architecture.md
  docs/baseclusters.md
  docs/concepts.md
  docs/contributing.md
  docs/design.md
  docs/dev_setup.md
  docs/docs_help.md
  docs/gen2_Tutorial.md
  docs/help.md
  docs/images/architecture
  docs/images/architecture.drawio
  docs/images/architecture_diagram.png
  docs/images/architecture_diagram_large.png
  docs/images/arlon_gen2.drawio
  docs/images/arlon_gen2.png
  docs/images/graphic_arlon-hero.svg
  docs/images/logo_arlon.svg
  docs/installation.md
  docs/tutorial.md
  mkdocs.yml
Labels: documentation

#384 User docs for AppProfiles (a.k.a. gen2 profiles and apps)
  docs/appprofiles.md
Labels: documentation, User Guide, size:S

#389 [v0.9] skip docs site push from CI
  .github/workflows/ci.yml
  docs/README.md
  docs/images/favicon-16x16.png
  docs/images/favicon-32x32.png
  docs/images/logo_arlon-stroke.svg
  docs/images/pictogram_arlon-stroke.svg
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: documentation

#388 Skip docs site deployment from CI (.github/workflows/ci.yml)
  .github/workflows/ci.yml
Labels: documentation

#391 [v0.9] [docs] Fix favicons
  docs/images/favicon-16x16.png
  docs/images/favicon-32x32.png
Labels: bug, documentation

#365 Add docs for init and install command, describe declarative examples, change repo-revision, change trigger for documentation deployment
  cmd/cluster/create.go
  docs/installation.md
  go.mod
Labels: documentation, sprint13

#390 [v0.3] skip docs site push from CI and backport docs infra updates from main
  .github/workflows/ci.yml
  docs/README.md
  docs/contributing.md
  docs/images/architecture.drawio
  docs/images/architecture_diagram.png
  docs/images/architecture_diagram_large.png
  docs/images/favicon-16x16.png
  docs/images/favicon-32x32.png
  docs/images/logo_arlon-stroke.svg
  docs/images/logo_arlon.svg
  docs/images/pictogram_arlon-stroke.svg
  docs/installation.md
  docs/requirements.txt
  docs/stylesheets/extra.css
  docs/tutorial.md
  mkdocs.yml
  overrides/main.html
Labels: documentation

#393 Hide CLI commands and docs / examples for gen1 clusters
  cmd/cluster/cluster.go
  cmd/cluster/deploy.go
  cmd/cluster/ngupdate.go
  cmd/cluster/update.go
  docs/README.md
  docs/appprofiles.md
  docs/clustertemplate.md
  docs/concepts.md
  docs/design.md
  docs/gen2_Tutorial.md
  main.go
Labels: documentation

#395 change GH Actions triggers for v0.10
  .github/workflows/ci.yml
  .github/workflows/e2e.yaml
  .github/workflows/goreleaser.yaml
  .github/workflows/trivy.yml
Labels: release-checklist

#397 change GH Actions envs for v0.9 (#395)
  .github/workflows/ci.yml
  .github/workflows/goreleaser.yaml
  .github/workflows/trivy.yml
Labels: size:xs, release-checklist

#398 change GH Actions env for v0.3
  .github/workflows/ci.yml
  .github/workflows/goreleaser.yaml
  .github/workflows/trivy.yml
Labels: size:xs, release-checklist

#399 upgrade go version
  Dockerfile
  testing/ubuntu_devel_prereqs.sh
Labels: release-checklist

#400 upgrade go version
  Dockerfile
  testing/ubuntu_devel_prereqs.sh
Labels: size:xs, release-checklist
