Repository arlonproj/arlon, pull requests merged in 2022-10, with the labels that each got.

#271 Removed flag kubeconfigPath from verify command
  cmd/verify/verify.go
Labels: enhancement, size:xs, sprint 6

#272 [Backport][v0.9]Added documentation for `arlon cluster ngupdate` command in the readme
  README.md
  docs/README.md
Labels: documentation, size:xs

#262 fix #248 - support for several AWS MachinePool types
  pkg/basecluster/data.go
Labels: enhancement
