Repository arlonproj/arlon, pull requests merged in 2022-09, with the labels that each got.

#190 change trigger for goreleaser ci
  .github/workflows/goreleaser.yaml
Labels: enhancement

#198 fix make test on Ubuntu for main by updating controller-gen to 0.9.2
  Makefile
  config/crd/bases/core.arlon.io_callhomeconfigs.yaml
  config/crd/bases/core.arlon.io_clusterregistrations.yaml
  config/crd/bases/core.arlon.io_profiles.yaml
Labels: bug

#199 Fix `make test` for v0.3 branch by updating controller-gen to v0.9.2
  Makefile
  api/v1/groupversion_info.go
  config/crd/bases/core.arlon.io_callhomeconfigs.yaml
  config/crd/bases/core.arlon.io_clusterregistrations.yaml
  config/crd/bases/core.arlon.io_profiles.yaml
  config/rbac/role.yaml
Labels: bug

#196 Fix profile delete bug.
  cmd/profile/delete.go
  pkg/profile/delete.go
Labels: bug

#208 Added instructions to download the CLI in installation section
  README.md
Labels: documentation

#216 Update golang from version 1.19 to 1.19.1 in Dockerfile
  Dockerfile
  version
Labels: enhancement, size:xs

#217 Minor updates to design.md , README.md
  README.md
  docs/design.md
Labels: documentation, size:xs

#231 [Backport][v0.3] Fix profile delete bug
  cmd/profile/delete.go
  pkg/profile/delete.go
Labels: size:xs

#232 Minor dependency upgrades for k8s1.22 aws-sdk-go etc
  go.mod
  go.sum
  version
Labels: size:xs

#242 [docs] Backport docs fixes from main
  README.md
  docs/README.md
  docs/design.md
Labels: documentation

#243 [Backport] fix #234 - add renaming config for EKSConfigTemplate
  pkg/basecluster/data.go
Labels: bug
