Repository arlonproj/arlon, pull requests merged in 2023-01, with the labels that each got.

#403 CI fixes, using GITHUB_TOKEN, change codecov comment layout and rename basecluster to cluster template
  .github/workflows/ci.yml
  .github/workflows/e2e.yaml
  .github/workflows/goreleaser.yaml
  cmd/basecluster/basecluster.go
  cmd/basecluster/prepare.go
  cmd/basecluster/preparegit.go
  cmd/basecluster/validate.go
  cmd/basecluster/validategit.go
  cmd/cluster/create.go
  cmd/cluster/list.go
  cmd/initialize/init.go
  codecov.yml
  docs/gen2_Tutorial.md
  pkg/basecluster/errors.go
  pkg/basecluster/prepare.go
  pkg/basecluster/validate.go
  pkg/cluster/get.go
  testing/README.md
Labels: good first issue, size:S, in_code_review, sprint14

#405 CI fixes backport to 0.9
  .github/workflows/ci.yml
  .github/workflows/goreleaser.yaml
Labels: size:xs, in_code_review, sprint14

#404 Backport to v0.10 CI fixes, using GITHUB_TOKEN, change codecov comment layout and rename basecluster to cluster template (#403)
  .github/workflows/ci.yml
  .github/workflows/e2e.yaml
  .github/workflows/goreleaser.yaml
  cmd/basecluster/basecluster.go
  cmd/basecluster/prepare.go
  cmd/basecluster/preparegit.go
  cmd/basecluster/validate.go
  cmd/basecluster/validategit.go
  cmd/cluster/create.go
  cmd/cluster/list.go
  cmd/initialize/init.go
  codecov.yml
  docs/gen2_Tutorial.md
  pkg/basecluster/errors.go
  pkg/basecluster/prepare.go
  pkg/basecluster/validate.go
  pkg/cluster/get.go
  testing/README.md
Labels: size:xs, in_code_review, sprint14

#409 Issue #407 : [docs] : Disable theme toggle between default (light) and dark (slate)
  mkdocs.yml
Labels: documentation, size:xs, in_code_review

#408 issue #407 [docs] [v0.10] disable dark mode
  mkdocs.yml
Labels: documentation

#406 CI fixes backport v0.3
  .github/workflows/ci.yml
  .github/workflows/goreleaser.yaml
Labels: size:xs, in_code_review, sprint14

#401 restructure concepts.md to prioritize gen2 profiles and clusters
  docs/concepts.md
  docs/gen1_profiles.md
Labels: documentation

#414 [docs] [v0.10] restructure concepts.md to prioritize gen2 profiles and clusters
  docs/concepts.md
  docs/gen1_profiles.md
Labels: documentation

#425 add version and version check docs
  cmd/version/check.go
  docs/gen2_Tutorial.md
Labels: documentation, User Guide, size:xs, in_code_review

#427 add version and version check docs to v0.10 (#425)
  cmd/version/check.go
  docs/gen2_Tutorial.md
Labels: documentation, User Guide, size:xs, backport

#410 CAS E2E test
  .github/workflows/e2eCas.yaml
  Makefile
  cmd/initialize/init.go
  testing/e2e-cas/00-cas/00-assert.yaml
  testing/e2e-cas/00-cas/00-cascluster.yaml
  testing/e2e-cas/01-cas-cleanup/00-delete.yaml
  testing/e2e-cas/01-cas-cleanup/00-errors.yaml
  testing/e2e_cas_setup.sh
  testing/e2e_cas_teardown.sh
  testing/eksctl_config.yaml
Labels: size:M, testing

#433 [docs infra] bump mkdocs material theme, mermaid JS diagrams
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, enhancement

#438 [Backport][v0.10] Adding plural version of commands
  cmd/app/app.go
  cmd/appprofile/appprofile.go
  cmd/basecluster/basecluster.go
  cmd/bundle/bundle.go
  cmd/cluster/cluster.go
  cmd/profile/profile.go
Labels: size:xs, backport

#431 Upgrade Argocd to release-2.5
  .goreleaser.yaml
  Dockerfile
  Makefile
  argorc
  capirc
  cmd/app/create.go
  controllers/applicationset_controller.go
  go.mod
  go.sum
  pkg/app/app.go
  pkg/appprofile/appprofile_test.go
  pkg/appprofile/reconcile.go
  pkg/controller/controller.go
  pkg/ctrlruntimeclient/ctrl_runt_client.go
  pkg/install/aws.go
  testing/ubuntu_devel_prereqs.sh
Labels: dependencies, size:M, Requirement
